### ISSUE TITLE
fail2ban-block-ip-range and recidive

### ISSUE THREAD

**Issue by jaccol** [WKnak/fail2ban-block-ip-range#14]
Hi,

In my `fail2ban` setup I enabled `recidive`. This will ban IP's that are banned multiple times to be banned for longer (1 week in the example config)
`recidive` will accomplish this by looking through `/var/log/fail2ban.log` and tracking how often an IP is banned.

`fail2ban-block-ip-range` recommends to run every 5 minutes. It will create a ban NOTICE every 5 minutes, if applicable. And `recidive` will pick this up as multiple offenses.

Result of this is that a relatively small set of bad traffic will always block a complete network for a week.

The best workaround I can think of is to let `fail2ban-block-ip-range` have it's own jail and have `recidive` ignore that jail.

This would have the effect that all jails work as normal, if a network behaves badly it will be picked up by `fail2ban-block-ip-range` and the network will be blocked according to the rules of that. If an IP is a repeat offender, that IP will be blocked for longer. Said otherwise, both are trackers of the same logfile and both will come to their own conclusions, without interference.

Any thoughts?

Jacco

**Comment by pbiering** [comment]
can make sense, question is how many config files need to be tweaked here and can this be finally packaged as fail2ban "add-on" in the RPM and enabled by a config option?

**Comment by jaccol** [comment]
I was wrong.

I thought I noticed said behavior in the logfile. And I thought I could understand that with glancing over the `recidive` regex. When trying to understand the issue better, I could not see it again in the log.
The regex that `recidive` uses is `<HOST>` which gets replaced by `r"""(?:\d{1,3}\.){3}\d{1,3}"""`. This means that `<HOST>` does not match CIDR notation.
