### ISSUE TITLE
SyntaxWarning: invalid escape sequence

### ISSUE THREAD

**Issue by octavsly** [WKnak/fail2ban-block-ip-range#20]
/usr/local/bin/fail2ban-block-ip-range.py:50: SyntaxWarning: invalid escape sequence '\d'
  age_pattern = re.compile("^(\d+)([smhdw])$")
/usr/local/bin/fail2ban-block-ip-range.py:80: SyntaxWarning: invalid escape sequence '\['
  fail2ban_log_pattern = re.compile("^([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}).* fail2ban.filter.*\[[0-9]+\]:.*\[([^]]+)\] Found ([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})")
MAXAGE not valid: 1

[fail2ban.log](https://github.com/user-attachments/files/15905925/fail2ban.log)

**Comment by pbiering** [comment]
Not seen during tests, which Python version do you use?

**Comment by pbiering** [comment]
Line 50 issue fixed only so far

**Comment by pbiering** [comment]
Line 80 issue: tested with Python 2.7.5 of EL7, no error message seen. 

Can you try following fix to escape `]` -> `\]` inside the negation set, because this is the only bracket which can potentially cause such legacy version issue imho.

`\[([^]]+)\] Found` -> `\[([^\]]+)\] Found`

**Comment by octavsly** [comment]
> Not seen during tests, which Python version do you use?

python 3.12

**Comment by pbiering** [comment]
thank you, credits to "pyupgrade" supporting fixing this issue in same PR.
